### ISSUE TITLE
Doesn't detect spaces when using chaining arrows syntax ("Class ['A'] -> Class ['B']")

### ISSUE THREAD

**Issue by gdubicki** [voxpupuli/puppet-lint-resource_reference_syntax#14]
I understand that this is more of a missing feature than a bug but it would be cool if you could add this.

Example of code that should trigger an error:

```
Class ['redis::install']
    -> Class ['redis::firewall']
    -> Class ['redis::config']
    ~> Class ['redis::service']
```

**Comment by tuxmea** [comment]
@gdubicki  Many thanks for reporting the issue. I published new version to rubygems.

**Comment by gdubicki** [comment]
Wow, that was quick! Thank you @tuxmea !

**Comment by gdubicki** [comment]
But actually it still doesn't detect issues in my code, tested versions 1.0.11 and 1.0.13, @tuxmea .

Example code for which it doesn't work:

```
# (...)

class dashing_wrapper (
  $gem_name                 = ['dashing', 'thin'],
  $monitoring               = true,
  $dashboard                = 'default',
  $dashing_dependencies     = ['ruby', 'ruby-devel', 'nodejs', 'gcc-c++', 'rubygem-bundler', 'libxml2-devel', 'libcurl-devel', 'patch', 'rubygem-nokogiri'],
  $dashing_dir              = '/opt/dashing',
  $dashing_user             = 'dashing',
  $dashing_group            = 'dashing',
  $thin_package             = 'thin',
  $instance_auth_token      = undef,
  $instance_routes          = ':ops, :graph'
) {

  contain dashing_wrapper::service
  contain dashing_wrapper::monitoring
  contain dashing_wrapper::dashboards
  contain dashing_wrapper::widgets
  contain dashing_wrapper::database
  contain dashing_wrapper::config
  contain dashing_wrapper::jobs
  contain dashing_wrapper::nagiosreporter

  Class ['dashing_wrapper::dashboards']
  -> Class ['dashing_wrapper::widgets'   ]
  -> Class ['dashing_wrapper::database'  ]
  -> Class ['dashing_wrapper::config'    ]
  -> Class ['dashing_wrapper::jobs'      ]
  ~> Class ['dashing_wrapper::service'   ]
  -> Class ['dashing_wrapper::monitoring']
  -> Class ['dashing_wrapper::nagiosreporter']

(...)

}
```

PS I am pretty sure I reported it already for 1.0.11 but my comment seems to have disappeared..

**Comment by tuxmea** [comment]
Ah!!! Class is different to Type (in puppet-lint lexer). Many thanks for raising this issue. I am working on a solution. Going to update later today.

**Comment by tuxmea** [comment]
fixed via https://github.com/voxpupuli/puppet-lint-resource_reference_syntax/commit/01c75b1b2c300e2cceaa8cd55d350eec5b3cea5e

**Comment by gdubicki** [comment]
I confirm that v. 1.0.14 works correctly. Many thanks @tuxmea !
